name: release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-v1-${{ hashFiles('**/package-lock.json') }}
      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: demo
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
